use serde::{Deserialize, Serialize};

/// Report generated by the ConfidenceAnalyzer
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct ConfidenceReport {
    /// Weighted composite score from 0.0 to 1.0
    pub confidence_score: f64,
    /// Ratio of hedging phrases to total sentences
    pub hedging_ratio: f64,
    /// Density of assertions (1.0 - hedging_ratio)
    pub assertion_density: f64,
    /// Score of specific items (numbers, paths, code blocks, URLs)
    pub specificity_score: f64,
    /// List of detected self-contradictions
    pub self_contradictions: Vec<String>,
    /// Categorized confidence level: HIGH_CONFIDENCE, MEDIUM_CONFIDENCE, or LOW_CONFIDENCE
    pub verdict: String,
    /// Suggestions for improving the text's confidence
    pub suggestions: Vec<String>,
}

/// Analyzer that calculates confidence scores based on text patterns
pub struct ConfidenceAnalyzer;

impl ConfidenceAnalyzer {
    /// Analyzes the provided text and returns a ConfidenceReport
    pub fn analyze(text: &str) -> ConfidenceReport {
        if text.trim().is_empty() {
            return ConfidenceReport {
                confidence_score: 0.0,
                hedging_ratio: 0.0,
                assertion_density: 0.0,
                specificity_score: 0.0,
                self_contradictions: vec![],
                verdict: "LOW_CONFIDENCE".to_string(),
                suggestions: vec!["Provide some text to analyze.".to_string()],
            };
        }

        let sentences: Vec<&str> = text
            .split(['.', '!', '?', '\n'])
            .map(|s| s.trim())
            .filter(|s| !s.is_empty())
            .collect();

        if sentences.is_empty() {
            return ConfidenceReport {
                confidence_score: 0.0,
                hedging_ratio: 0.0,
                assertion_density: 0.0,
                specificity_score: 0.0,
                self_contradictions: vec![],
                verdict: "LOW_CONFIDENCE".to_string(),
                suggestions: vec!["Text must contain valid sentences.".to_string()],
            };
        }

        let total_sentences = sentences.len() as f64;

        const HEDGING_PHRASES: &[&str] = &[
            "maybe", "probably", "i think", "might", "could be", "not sure", "perhaps", "possibly",
            "it seems", "i believe", "i guess", "it appears", "likely", "unlikely", "not certain",
            "unclear", "debatable", "in my opinion", "it depends", "hard to say",
        ];

        let mut hedging_count: f64 = 0.0;
        for sentence in &sentences {
            let lower_sentence = sentence.to_lowercase();
            if HEDGING_PHRASES.iter().any(|&p| lower_sentence.contains(p)) {
                hedging_count += 1.0;
            }
        }

        let hedging_ratio = hedging_count / total_sentences;
        let assertion_density = 1.0 - hedging_ratio;

        let words: Vec<&str> = text.split_whitespace().collect();
        let word_count = words.len() as f64;
        let mut specific_items: f64 = 0.0;

        let mut in_code_block = false;
        for line in text.lines() {
            if line.contains("```") {
                in_code_block = !in_code_block;
                if in_code_block {
                    specific_items += 1.0;
                }
            }
        }

        for word in &words {
            if word.chars().any(|c| c.is_ascii_digit())
                || ((word.contains('/') || word.contains('\\')) && word.contains('.'))
                || word.starts_with("http://")
                || word.starts_with("https://")
                || word.contains('_')
                || (word.len() > 1 && word.chars().skip(1).any(|c| c.is_uppercase()))
            {
                specific_items += 1.0;
            }
        }

        let expected_specifics = if word_count > 0.0 {
            word_count / 10.0
        } else {
            1.0
        };
        let specificity = if expected_specifics > 0.0 {
            (specific_items / expected_specifics).min(1.0)
        } else {
            0.0
        };

        const NEGATION_PREFIXES: &[&str] = &[
            "no ",
            "not ",
            "don't ",
            "never ",
            "without ",
            "disable ",
            "must not ",
            "do not ",
            "cannot ",
            "shouldn't ",
            "won't ",
            "isn't ",
            "aren't ",
        ];

        let mut self_contradictions = Vec::new();
        let mut negative_concepts = Vec::new();
        let mut positive_sentences = Vec::new();

        for sentence in &sentences {
            let lower_sentence = sentence.to_lowercase();
            let mut found_neg = false;
            for &neg in NEGATION_PREFIXES {
                if let Some(idx) = lower_sentence.find(neg) {
                    let concept = &lower_sentence[idx + neg.len()..];
                    let word_concept = concept
                        .split_whitespace()
                        .take(3)
                        .collect::<Vec<_>>()
                        .join(" ");
                    if !word_concept.is_empty() {
                        negative_concepts.push(word_concept);
                    }
                    found_neg = true;
                    break;
                }
            }
            if !found_neg {
                positive_sentences.push(lower_sentence);
            }
        }

        for concept in &negative_concepts {
            for pos in &positive_sentences {
                if pos.contains(concept) {
                    self_contradictions
                        .push(format!("Contradiction found on concept: '{}'", concept));
                    break;
                }
            }
        }

        let contradiction_penalty = if !self_contradictions.is_empty() {
            1.0
        } else {
            0.0
        };

        const AI_FILLER_PHRASES: &[&str] = &[
            "as an ai",
            "i'd be happy to",
            "let me explain",
            "certainly!",
            "of course!",
            "great question",
            "i understand",
            "absolutely",
            "sure thing",
            "here's what i",
            "i'll help you",
            "let me help",
        ];

        let mut filler_count: f64 = 0.0;
        let lower_text = text.to_lowercase();
        for &filler in AI_FILLER_PHRASES {
            if lower_text.contains(filler) {
                filler_count += 1.0;
            }
        }
        let filler_penalty = (filler_count * 0.1f64).min(1.0f64);

        let base_confidence = 0.40 * assertion_density
            + 0.25 * specificity
            + 0.25 * (1.0 - contradiction_penalty)
            + 0.10 * (1.0 - filler_penalty);

        let confidence_score = (base_confidence * (1.0 - 0.5 * hedging_ratio)).clamp(0.0, 1.0);

        let verdict = if confidence_score > 0.75 {
            "HIGH_CONFIDENCE".to_string()
        } else if confidence_score >= 0.5 {
            "MEDIUM_CONFIDENCE".to_string()
        } else {
            "LOW_CONFIDENCE".to_string()
        };

        let mut suggestions = Vec::new();
        if hedging_ratio > 0.3 {
            suggestions.push("Reduce hedging phrases like 'maybe' and 'probably'.".to_string());
        }
        if specificity < 0.5 {
            suggestions.push(
                "Include more specific references (numbers, code blocks, URLs, file paths)."
                    .to_string(),
            );
        }
        if !self_contradictions.is_empty() {
            suggestions.push("Resolve self-contradictions in the text.".to_string());
        }

        ConfidenceReport {
            confidence_score,
            hedging_ratio,
            assertion_density,
            specificity_score: specificity,
            self_contradictions,
            verdict,
            suggestions,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_high_confidence() {
        let text = "We must deploy to /var/www/html immediately. The configuration requires 5 nodes. \n```bash\nservice restart\n```\nThis is the optimal solution.";
        let report = ConfidenceAnalyzer::analyze(text);
        assert!(
            report.confidence_score > 0.7,
            "Expected > 0.7, got {}",
            report.confidence_score
        );
        assert_eq!(report.verdict, "HIGH_CONFIDENCE");
    }

    #[test]
    fn test_low_confidence() {
        let text = "I think maybe we should possibly try something else. Probably it depends on the situation. I'm not sure if it seems like a good idea.";
        let report = ConfidenceAnalyzer::analyze(text);
        assert!(
            report.confidence_score < 0.5,
            "Expected < 0.5, got {}",
            report.confidence_score
        );
        assert_eq!(report.verdict, "LOW_CONFIDENCE");
    }

    #[test]
    fn test_self_contradiction() {
        let text = "I will deploy the update. Do not deploy the update. This is fine.";
        let report = ConfidenceAnalyzer::analyze(text);
        assert!(!report.self_contradictions.is_empty());
    }

    #[test]
    fn test_empty_text() {
        let text = "";
        let report = ConfidenceAnalyzer::analyze(text);
        assert_eq!(report.confidence_score, 0.0);
        assert_eq!(report.verdict, "LOW_CONFIDENCE");
    }
}
