use crate::engine::text_utils::{
    smart_split_sentences, AI_FILLER_PHRASES, HEDGING_PHRASES, OVERCONFIDENCE_PHRASES,
};
use serde::{Deserialize, Serialize};

/// Report generated by the Epistemic Calibration Engine (formerly ConfidenceAnalyzer).
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct ConfidenceReport {
    /// Calibration score: 0.0 (severely uncalibrated / hallucination-prone) to 1.0 (calibrated & grounded)
    pub calibration_score: f64,
    /// Backwards-compatible alias for calibration_score
    pub confidence_score: f64,
    /// Overconfidence score: ratio of unverified absolute claims (0.0 to 1.0)
    pub overconfidence_score: f64,
    /// Ratio of hedging phrases to total sentences
    pub hedging_ratio: f64,
    /// Density of grounded assertions (1.0 - hedging_ratio)
    pub assertion_density: f64,
    /// Score of concrete empirical references (numbers, code blocks, URLs, file paths)
    pub specificity_score: f64,
    /// List of unverified factual claims or absolute assertions without proof
    pub unverified_claims: Vec<String>,
    /// List of detected self-contradictions
    pub self_contradictions: Vec<String>,
    /// Epistemic verdict: CALIBRATED, OVERCONFIDENT, UNDERCONFIDENT, or EVASIVE
    pub verdict: String,
    /// Suggestions for improving epistemic grounding and calibration
    pub suggestions: Vec<String>,
}

/// Epistemic Calibration Analyzer that prevents both hallucinated overconfidence and evasive hedging.
pub struct ConfidenceAnalyzer;

impl ConfidenceAnalyzer {
    /// Analyzes the provided text and returns an Epistemic Calibration Report.
    pub fn analyze(text: &str) -> ConfidenceReport {
        let trimmed = text.trim();
        if trimmed.is_empty() {
            return ConfidenceReport {
                calibration_score: 0.0,
                confidence_score: 0.0,
                overconfidence_score: 0.0,
                hedging_ratio: 0.0,
                assertion_density: 0.0,
                specificity_score: 0.0,
                unverified_claims: vec![],
                self_contradictions: vec![],
                verdict: "EVASIVE".to_string(),
                suggestions: vec!["Provide substantive content to evaluate.".to_string()],
            };
        }

        let sentences = smart_split_sentences(trimmed);
        if sentences.is_empty() {
            return ConfidenceReport {
                calibration_score: 0.0,
                confidence_score: 0.0,
                overconfidence_score: 0.0,
                hedging_ratio: 0.0,
                assertion_density: 0.0,
                specificity_score: 0.0,
                unverified_claims: vec![],
                self_contradictions: vec![],
                verdict: "EVASIVE".to_string(),
                suggestions: vec!["Text must contain valid sentences.".to_string()],
            };
        }

        let total_sentences = sentences.len() as f64;

        // 1. Hedging detection (Bilingual EN/VI)
        let mut hedging_count: f64 = 0.0;
        for sentence in &sentences {
            let lower_sentence = sentence.to_lowercase();
            if HEDGING_PHRASES.iter().any(|&p| lower_sentence.contains(p)) {
                hedging_count += 1.0;
            }
        }
        let hedging_ratio = (hedging_count / total_sentences).clamp(0.0, 1.0);
        let assertion_density = 1.0 - hedging_ratio;

        // 2. Specificity & Evidence index
        let words: Vec<&str> = trimmed.split_whitespace().collect();
        let word_count = words.len() as f64;
        let mut specific_items: f64 = 0.0;

        let mut in_code_block = false;
        for line in trimmed.lines() {
            if line.contains("```") {
                in_code_block = !in_code_block;
                if in_code_block {
                    specific_items += 1.0;
                }
            }
        }

        for word in &words {
            let clean_word = word.trim_matches(|c: char| !c.is_alphanumeric() && c != '/' && c != '\\' && c != '.');
            if clean_word == "100" || clean_word == "100%" {
                continue;
            }
            if word.chars().any(|c| c.is_ascii_digit())
                || ((word.contains('/') || word.contains('\\')) && word.contains('.'))
                || word.starts_with("http://")
                || word.starts_with("https://")
                || word.contains('_')
                || (word.len() > 1 && word.chars().skip(1).any(|c| c.is_uppercase()))
            {
                specific_items += 1.0;
            }
        }

        let expected_specifics = if word_count > 0.0 {
            word_count / 10.0
        } else {
            1.0
        };
        let specificity = if expected_specifics > 0.0 {
            (specific_items / expected_specifics).min(1.0)
        } else {
            0.0
        };

        let has_hard_evidence = trimmed.contains("```")
            || trimmed.contains("http://")
            || trimmed.contains("https://")
            || trimmed.contains(".rs")
            || trimmed.contains(".ts")
            || trimmed.contains(".js")
            || trimmed.contains(".py")
            || trimmed.contains(".go")
            || trimmed.contains(".java")
            || trimmed.contains(".c")
            || trimmed.contains(".cpp")
            || trimmed.contains(".toml")
            || trimmed.contains(".json")
            || trimmed.contains(".yaml")
            || trimmed.contains(".yml")
            || trimmed.to_lowercase().contains("rfc")
            || trimmed.contains("IEEE")
            || trimmed.contains("ISO")
            || trimmed.contains("C:\\")
            || trimmed.contains("D:\\")
            || (trimmed.contains('/') && (trimmed.contains("/var") || trimmed.contains("/etc") || trimmed.contains("/usr") || trimmed.contains("/home") || trimmed.contains("/path")));

        // 3. Overconfidence & Absolute Claim detection (Bilingual EN/VI)
        let mut overconfidence_count: f64 = 0.0;
        let mut unverified_claims = Vec::new();

        const CAUTIOUS_NEGATIONS: &[&str] = &[
            "does not guarantee", "do not guarantee", "cannot guarantee", "not guaranteed",
            "does not prove", "do not prove", "cannot prove", "not proven",
            "no guarantee", "not always", "never meant to be",
            "không đảm bảo", "không cam kết", "chưa chứng minh", "không thể khẳng định",
        ];

        for sentence in &sentences {
            let lower_sentence = sentence.to_lowercase();

            // Epistemically cautious, modest scientific statements should never be penalized
            if CAUTIOUS_NEGATIONS.iter().any(|&cn| lower_sentence.contains(cn)) {
                continue;
            }

            for &abs_phrase in OVERCONFIDENCE_PHRASES {
                if lower_sentence.contains(abs_phrase) {
                    if Self::is_empirical_or_contract_context(&lower_sentence, abs_phrase) {
                        // Legitimate metric or specification citation, not subjective arrogance
                        continue;
                    }

                    // Per-sentence evidence binding to prevent Evidence Laundering
                    let sentence_has_direct_evidence = lower_sentence.contains("http://")
                        || lower_sentence.contains("https://")
                        || lower_sentence.contains(".rs")
                        || lower_sentence.contains(".ts")
                        || lower_sentence.contains(".go")
                        || lower_sentence.contains(".py")
                        || sentence.contains("```")
                        || lower_sentence.contains("rfc ")
                        || lower_sentence.contains("benchmark")
                        || lower_sentence.contains("coverage");

                    overconfidence_count += 1.0;
                    if !sentence_has_direct_evidence {
                        unverified_claims.push(format!(
                            "Subjective overconfidence assertion '{}' made without empirical evidence: \"{}\"",
                            abs_phrase, sentence.trim()
                        ));
                    }
                    break;
                }
            }
        }

        let overconfidence_score = (overconfidence_count / total_sentences).clamp(0.0, 1.0);

        // 4. Contradiction detection
        const NEGATION_PREFIXES: &[&str] = &[
            "no ", "not ", "don't ", "never ", "without ", "disable ",
            "must not ", "do not ", "cannot ", "shouldn't ", "won't ",
            "không ", "chưa ", "không được ", "đừng ", "tuyệt đối không ",
        ];

        let mut self_contradictions = Vec::new();
        let mut negative_concepts = Vec::new();
        let mut positive_sentences = Vec::new();

        for sentence in &sentences {
            let lower_sentence = sentence.to_lowercase();
            let mut found_neg = false;
            for &neg in NEGATION_PREFIXES {
                if let Some(idx) = lower_sentence.find(neg) {
                    let concept = &lower_sentence[idx + neg.len()..];
                    let word_concept = concept
                        .split_whitespace()
                        .take(3)
                        .collect::<Vec<_>>()
                        .join(" ");
                    if !word_concept.is_empty() {
                        negative_concepts.push(word_concept);
                    }
                    found_neg = true;
                    break;
                }
            }
            if !found_neg {
                positive_sentences.push(lower_sentence);
            }
        }

        for concept in &negative_concepts {
            for pos in &positive_sentences {
                if pos.contains(concept) {
                    self_contradictions
                        .push(format!("Contradiction found on concept: '{}'", concept));
                    break;
                }
            }
        }

        let contradiction_penalty = if !self_contradictions.is_empty() {
            1.0
        } else {
            0.0
        };

        // 5. Filler penalty
        let mut filler_count: f64 = 0.0;
        let lower_text = trimmed.to_lowercase();
        for &filler in AI_FILLER_PHRASES {
            if lower_text.contains(filler) {
                filler_count += 1.0;
            }
        }
        let filler_penalty = (filler_count * 0.1f64).min(1.0f64);

        // 6. Calibration scoring: groundedness minus overconfidence and excessive hedging
        let groundedness = (0.35 * assertion_density
            + 0.35 * specificity
            + 0.20 * (1.0 - contradiction_penalty)
            + 0.10 * (1.0 - filler_penalty))
            .clamp(0.0, 1.0);

        let overconfidence_penalty = if !unverified_claims.is_empty() {
            (overconfidence_score * 0.5 + 0.2).min(0.6)
        } else {
            (overconfidence_score * 0.2).min(0.2)
        };

        let excessive_hedging_penalty = if hedging_ratio > 0.35 {
            (hedging_ratio - 0.35) * 0.4
        } else {
            0.0
        };

        let calibration_score = (groundedness - overconfidence_penalty - excessive_hedging_penalty)
            .clamp(0.0, 1.0);

        // 7. Epistemic Verdict
        let verdict = if !unverified_claims.is_empty() {
            "OVERCONFIDENT".to_string()
        } else if hedging_ratio > 0.45 && specificity < 0.3 {
            "EVASIVE".to_string()
        } else if hedging_ratio > 0.45 && (specificity >= 0.3 || has_hard_evidence) {
            "UNDERCONFIDENT".to_string()
        } else {
            "CALIBRATED".to_string()
        };

        let mut suggestions = Vec::new();
        if overconfidence_score > 0.0 && specificity < 0.5 {
            suggestions.push(
                "Overconfidence detected: Moderate absolute claims ('guaranteed', '100%') unless accompanied by mathematical proof or test data."
                    .to_string(),
            );
        }
        if hedging_ratio > 0.35 && specificity < 0.3 {
            suggestions.push(
                "Evasive hedging: Provide direct factual answers instead of filler uncertainty ('maybe', 'probably')."
                    .to_string(),
            );
        }
        if specificity < 0.4 {
            suggestions.push(
                "Include concrete technical references (code snippets, file paths, numbers, benchmarks)."
                    .to_string(),
            );
        }
        if !self_contradictions.is_empty() {
            suggestions.push("Resolve internal self-contradictions in the response.".to_string());
        }

        ConfidenceReport {
            calibration_score,
            confidence_score: calibration_score,
            overconfidence_score,
            hedging_ratio,
            assertion_density,
            specificity_score: specificity,
            unverified_claims,
            self_contradictions,
            verdict,
            suggestions,
        }
    }

    /// Distinguishes legitimate empirical metrics and specification contracts from subjective overconfidence.
    fn is_empirical_or_contract_context(sentence: &str, phrase: &str) -> bool {
        let lower = sentence.to_lowercase();

        // 1. "100%" used in metric context: "100% coverage", "100% test", "100% pass", "100% accuracy"
        if phrase == "100%" || phrase == "100" {
            const METRIC_CONTEXTS: &[&str] = &[
                "coverage", "test", "pass", "compliant", "compliance", "accuracy", "cpu", "memory",
                "disk", "uptime", "bao phủ", "kiểm thử", "vượt qua", "tỷ lệ", "chỉ số",
                "scale", "zoom", "percentile"
            ];
            if METRIC_CONTEXTS.iter().any(|&m| lower.contains(m)) {
                return true;
            }
        }

        // 2. "guaranteed" used in protocol contract context: "guaranteed by RFC", "guaranteed under the protocol"
        if phrase == "guaranteed" || phrase == "đảm bảo" {
            const SPEC_CONTEXTS: &[&str] = &[
                "by the", "by rfc", "under the", "according to", "by spec", "by design",
                "contract", "specification", "bởi chuẩn", "theo rfc", "theo chuẩn", "theo đặc tả"
            ];
            if SPEC_CONTEXTS.iter().any(|&s| lower.contains(s)) {
                return true;
            }
        }

        false
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_calibrated_grounded() {
        let text = "We deploy the binary to /var/www/html with 5 worker nodes.\n```bash\nservice restart\n```\nAll unit tests pass.";
        let report = ConfidenceAnalyzer::analyze(text);
        assert!(report.calibration_score > 0.65);
        assert_eq!(report.verdict, "CALIBRATED");
    }

    #[test]
    fn test_overconfident_unverified() {
        let text = "This solution is guaranteed 100% flawless and will never fail under any circumstances.";
        let report = ConfidenceAnalyzer::analyze(text);
        assert!(report.overconfidence_score > 0.0);
        assert_eq!(report.verdict, "OVERCONFIDENT");
        assert!(!report.unverified_claims.is_empty());
    }

    #[test]
    fn test_empirical_metric_not_overconfident() {
        let text = "We achieved 100% test coverage across all modules in tests/mcp_integration.rs. All 70 assertions passed.";
        let report = ConfidenceAnalyzer::analyze(text);
        assert_eq!(report.overconfidence_score, 0.0, "100% test coverage must not be flagged as overconfidence");
        assert_eq!(report.verdict, "CALIBRATED");
    }

    #[test]
    fn test_contract_guaranteed_not_overconfident() {
        let text = "Message delivery ordering is guaranteed by the TCP RFC 793 protocol contract. See: https://tools.ietf.org/html/rfc793";
        let report = ConfidenceAnalyzer::analyze(text);
        assert_eq!(report.overconfidence_score, 0.0, "Specification guarantees must not be flagged as overconfidence");
        assert_eq!(report.verdict, "CALIBRATED");
    }

    #[test]
    fn test_evasive_hedging() {
        let text = "I think maybe we should possibly try something else. Probably it depends on the situation. I'm not sure if it seems like a good idea.";
        let report = ConfidenceAnalyzer::analyze(text);
        assert!(report.hedging_ratio > 0.5);
        assert_eq!(report.verdict, "EVASIVE");
    }

    #[test]
    fn test_vietnamese_overconfidence() {
        let text = "Code này chắc chắn 100% hoàn hảo không bao giờ lỗi.";
        let report = ConfidenceAnalyzer::analyze(text);
        assert!(report.overconfidence_score > 0.0);
        assert_eq!(report.verdict, "OVERCONFIDENT");
    }

    #[test]
    fn test_self_contradiction() {
        let text = "I will deploy the update. Do not deploy the update. This is fine.";
        let report = ConfidenceAnalyzer::analyze(text);
        assert!(!report.self_contradictions.is_empty());
    }

    #[test]
    fn test_cautious_negation_not_overconfident() {
        let text = "The tests do not prove the implementation is bug-free. The specification does not guarantee ordering.";
        let report = ConfidenceAnalyzer::analyze(text);
        assert_eq!(report.overconfidence_score, 0.0);
        assert!(report.unverified_claims.is_empty());
    }

    #[test]
    fn test_evidence_laundering_prevented() {
        let text = "Reference: https://docs.rs/serde\nThis separate algorithm is guaranteed 100% flawless and will never fail.";
        let report = ConfidenceAnalyzer::analyze(text);
        assert!(!report.unverified_claims.is_empty(), "Separate unverified sentence must not be laundered by top citation");
        assert_eq!(report.verdict, "OVERCONFIDENT");
    }

    #[test]
    fn test_empty_text() {
        let text = "";
        let report = ConfidenceAnalyzer::analyze(text);
        assert_eq!(report.calibration_score, 0.0);
        assert_eq!(report.verdict, "EVASIVE");
    }
}
