//! Foresight & Proactive Thinking Engine: Evaluates defensive design, edge case coverage, and plan diligence.

use crate::engine::text_utils::FORESIGHT_MARKERS;
use serde::{Deserialize, Serialize};

/// Report generated by the ForesightEngine.
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct ForesightReport {
    /// Coverage of error handling / defensive design patterns (0.0 to 1.0)
    pub defensive_coverage: f64,
    /// Coverage of edge case / boundary condition anticipation (0.0 to 1.0)
    pub edge_case_coverage: f64,
    /// Presence of testing and verification strategy (0.0 to 1.0)
    pub verification_coverage: f64,
    /// Ratio of planned tasks to requirements complexity
    pub plan_depth_ratio: f64,
    /// True if requirements are complex but plan is shallow or single-step
    pub is_lazy_plan: bool,
    /// Foresight and proactive engineering score (0.0 to 100.0)
    pub foresight_score: f64,
    /// Proactivity verdict: PROACTIVE, REACTIVE, or LAZY_PLAN
    pub verdict: String,
    /// Areas requiring deeper foresight or proactive engineering
    pub recommendations: Vec<String>,
}

pub struct ForesightEngine;

impl ForesightEngine {
    /// Checks whether a term is present affirmatively or negated by nearby negation tokens.
    /// Returns `(has_affirmative, has_negated)`.
    pub fn analyze_term_presence(text: &str, term: &str) -> (bool, bool) {
        const NEGATION_PREFIXES: &[&str] = &[
            "no ",
            "not ",
            "don't ",
            "never ",
            "without ",
            "lack of ",
            "lacks ",
            "chưa có ",
            "không có ",
            "không cần ",
            "bỏ qua ",
        ];

        let mut search_idx = 0;
        let mut found_affirmative = false;
        let mut found_negated = false;

        while let Some(rel_idx) = text[search_idx..].find(term) {
            let term_idx = search_idx + rel_idx;

            // Extract up to 30 characters safely along char boundaries
            let prefix = &text[..term_idx];
            let prefix_window = match prefix.char_indices().rev().nth(30) {
                Some((byte_idx, _)) => &prefix[byte_idx..],
                None => prefix,
            };

            let is_neg = NEGATION_PREFIXES
                .iter()
                .any(|&neg| prefix_window.ends_with(neg) || prefix_window.contains(neg));

            if is_neg {
                found_negated = true;
            } else {
                found_affirmative = true;
            }
            search_idx = term_idx + term.len();
        }

        (found_affirmative, found_negated)
    }

    /// Evaluates text, code snippet, and plan structure for proactive foresight.
    pub fn evaluate(
        text: Option<&str>,
        code: Option<&str>,
        requirements_count: usize,
        planned_tasks_count: usize,
    ) -> ForesightReport {
        let mut combined_content = String::new();
        if let Some(t) = text {
            combined_content.push_str(t);
            combined_content.push(' ');
        }
        if let Some(c) = code {
            combined_content.push_str(c);
        }
        let lower = combined_content.to_lowercase();

        // 1. Defensive design detection
        let defensive_terms = [
            "error",
            "result<",
            "option<",
            "try",
            "catch",
            "fallback",
            "timeout",
            "retry",
            "null",
            "none",
            "recover",
            "xử lý lỗi",
            "ngoại lệ",
            "dự phòng",
        ];
        let mut defensive_matches = 0;
        let mut explicit_defensive_negations = 0;
        for &term in &defensive_terms {
            let (affirmative, negated) = Self::analyze_term_presence(&lower, term);
            if affirmative {
                defensive_matches += 1;
            }
            if negated && !affirmative {
                explicit_defensive_negations += 1;
            }
        }
        let defensive_coverage = (defensive_matches as f64 / 3.0).min(1.0);

        // 2. Edge case and boundary condition detection
        let edge_case_terms = [
            "empty",
            "overflow",
            "boundary",
            "edge case",
            "limit",
            "zero",
            "concurrency",
            "trường hợp biên",
            "rỗng",
            "giới hạn",
            "tràn số",
        ];
        let mut edge_matches = 0;
        for &term in &edge_case_terms {
            let (affirmative, _) = Self::analyze_term_presence(&lower, term);
            if affirmative {
                edge_matches += 1;
            }
        }
        let edge_case_coverage = (edge_matches as f64 / 2.0).min(1.0);

        // 3. Verification & testing coverage
        let verification_terms = [
            "test",
            "assert",
            "verify",
            "benchmark",
            "validate",
            "kiểm thử",
            "xác thực",
        ];
        let mut verif_matches = 0;
        for &term in &verification_terms {
            let (affirmative, _) = Self::analyze_term_presence(&lower, term);
            if affirmative {
                verif_matches += 1;
            }
        }
        for &marker in FORESIGHT_MARKERS {
            let (affirmative, _) = Self::analyze_term_presence(&lower, marker);
            if affirmative {
                verif_matches += 1;
            }
        }
        let verification_coverage = (verif_matches as f64 / 3.0).min(1.0);

        // 4. Plan depth vs requirements complexity
        let req_count = requirements_count.max(1);
        let plan_depth_ratio = planned_tasks_count as f64 / req_count as f64;
        let is_lazy_plan = requirements_count >= 3 && planned_tasks_count <= 1;

        // 5. Composite foresight score
        let content_score =
            (defensive_coverage * 40.0 + edge_case_coverage * 30.0 + verification_coverage * 30.0).clamp(0.0, 100.0);
        let foresight_score = if is_lazy_plan {
            content_score.min(45.0)
        } else {
            content_score
        };

        let verdict = if is_lazy_plan {
            "LAZY_PLAN".to_string()
        } else if foresight_score >= 65.0 {
            "PROACTIVE".to_string()
        } else {
            "REACTIVE".to_string()
        };

        let mut recommendations = Vec::new();
        if explicit_defensive_negations > 0 {
            recommendations.push(
                "Negated Resilience Anti-Pattern: Explicit omission of defensive mechanisms (e.g. 'no timeout', 'no retry', 'without error handling'). Resilience requires positive implementation."
                    .to_string(),
            );
        }
        if is_lazy_plan {
            recommendations.push(
                "Lazy Plan Detected: Multiple complex requirements stated, but task breakdown is shallow (<=1 task). Decompose into distinct verifiable steps."
                    .to_string(),
            );
        }
        if defensive_coverage < 0.4 {
            recommendations.push(
                "Defensive Design Deficit: No error handling, timeout, or fallback mechanism identified. Consider failure modes."
                    .to_string(),
            );
        }
        if edge_case_coverage < 0.4 {
            recommendations.push(
                "Edge Case Blindspot: Consider boundary values (empty input, max bounds, concurrency, network drops)."
                    .to_string(),
            );
        }
        if verification_coverage < 0.4 {
            recommendations.push(
                "Missing Verification Strategy: Define automated tests or measurable validation criteria.".to_string(),
            );
        }

        ForesightReport {
            defensive_coverage,
            edge_case_coverage,
            verification_coverage,
            plan_depth_ratio,
            is_lazy_plan,
            foresight_score,
            verdict,
            recommendations,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_proactive_foresight() {
        let text = "We handle timeout, empty collections, and error fallback. Unit tests will verify race condition boundaries.";
        let report = ForesightEngine::evaluate(Some(text), None, 2, 4);

        assert_eq!(report.verdict, "PROACTIVE");
        assert!(report.foresight_score >= 65.0);
        assert!(!report.is_lazy_plan);
    }

    #[test]
    fn test_lazy_plan_detection() {
        let text = "I will implement the whole system in one go.";
        let report = ForesightEngine::evaluate(Some(text), None, 5, 1);

        assert!(report.is_lazy_plan);
        assert_eq!(report.verdict, "LAZY_PLAN");
        assert!(!report.recommendations.is_empty());
    }

    #[test]
    fn test_reactive_happy_path() {
        let text = "This function adds two numbers and returns the sum.";
        let report = ForesightEngine::evaluate(Some(text), None, 1, 1);

        assert_eq!(report.verdict, "REACTIVE");
        assert!(report.defensive_coverage < 0.5);
    }

    #[test]
    fn test_negation_trap_in_defensive_coverage() {
        let text = "There is no timeout, no retry, and without error handling in our client.";
        let report = ForesightEngine::evaluate(Some(text), None, 1, 1);

        assert_eq!(report.defensive_coverage, 0.0);
        assert!(report.recommendations.iter().any(|r| r.contains("Negated Resilience")));
    }
}
