//! Research Gate Engine: Forces AI to cite empirical evidence and verify claims before delivering output.

use crate::engine::text_utils::{smart_split_sentences, EVIDENCE_MARKERS, HEDGING_PHRASES};
use serde::{Deserialize, Serialize};

/// Report generated by the ResearchGate engine.
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct ResearchReport {
    /// Number of factual claims detected (versions, benchmarks, library compatibility, dates)
    pub factual_claims_count: usize,
    /// Number of empirical evidence citations detected (URLs, RFCs, paths, logs, test outputs)
    pub citations_count: usize,
    /// Evidence to claims ratio: citations / max(claims, 1)
    pub evidence_ratio: f64,
    /// Ratio of speculative statements to total sentences
    pub speculation_ratio: f64,
    /// True if multiple factual claims exist without supporting evidence
    pub has_research_deficit: bool,
    /// Factual claims flagged as ungrounded
    pub unverified_claims: Vec<String>,
    /// Concrete evidence sources detected
    pub detected_sources: Vec<String>,
    /// Grounding quality score (0.0 to 100.0)
    pub research_score: f64,
    /// Verdict: RESEARCH_GROUNDED, RESEARCH_DEFICIT, or THEORETICAL
    pub verdict: String,
    /// Actionable research recommendations
    pub recommendations: Vec<String>,
}

pub struct ResearchGate;

impl ResearchGate {
    /// Audits response text to verify that technical claims are backed by research and citations.
    pub fn audit(text: &str) -> ResearchReport {
        let trimmed = text.trim();
        if trimmed.is_empty() {
            return ResearchReport {
                factual_claims_count: 0,
                citations_count: 0,
                evidence_ratio: 1.0,
                speculation_ratio: 0.0,
                has_research_deficit: false,
                unverified_claims: vec![],
                detected_sources: vec![],
                research_score: 100.0,
                verdict: "THEORETICAL".to_string(),
                recommendations: vec!["Text is empty.".to_string()],
            };
        }

        let sentences = smart_split_sentences(trimmed);
        let total_sentences = sentences.len().max(1);

        let mut factual_claims = Vec::new();
        let mut detected_sources = Vec::new();
        let mut speculation_count = 0;

        for sentence in &sentences {
            let lower = sentence.to_lowercase();

            // 1. Evidence / Citation detection
            let mut has_citation = false;
            if lower.contains("http://") || lower.contains("https://") {
                detected_sources.push("Web URL / Documentation link".to_string());
                has_citation = true;
            }
            if lower.contains(".rs") || lower.contains(".ts") || lower.contains(".py") || lower.contains(".json") || lower.contains(".toml") {
                detected_sources.push("Source file path reference".to_string());
                has_citation = true;
            }
            if sentence.contains("```") {
                detected_sources.push("Code snippet / test execution block".to_string());
                has_citation = true;
            }
            for &marker in EVIDENCE_MARKERS {
                if lower.contains(marker) {
                    detected_sources.push(format!("Citation marker: '{}'", marker));
                    has_citation = true;
                    break;
                }
            }

            // 2. Factual claim detection: version strings, benchmarks, release dates
            let has_version_claim = lower.contains('v') && sentence.chars().any(|c| c.is_ascii_digit());
            let has_benchmark_claim = lower.contains("ms") || lower.contains("ops/s") || lower.contains("benchmark") || lower.contains("throughput");
            let has_spec_claim = lower.contains("supports") || lower.contains("compatible with") || lower.contains("hỗ trợ") || lower.contains("tương thích");

            if (has_version_claim || has_benchmark_claim || has_spec_claim) && !has_citation {
                factual_claims.push(sentence.trim().to_string());
            }

            // 3. Speculation detection
            if HEDGING_PHRASES.iter().any(|&h| lower.contains(h)) {
                speculation_count += 1;
            }
        }

        detected_sources.sort();
        detected_sources.dedup();

        let factual_claims_count = factual_claims.len();
        let citations_count = detected_sources.len();

        let evidence_ratio = if factual_claims_count == 0 {
            1.0
        } else {
            (citations_count as f64 / factual_claims_count as f64).min(2.0)
        };

        let speculation_ratio = speculation_count as f64 / total_sentences as f64;

        let has_research_deficit = factual_claims_count >= 2 && citations_count == 0;

        let base_score = if factual_claims_count == 0 {
            95.0
        } else {
            (evidence_ratio * 70.0 + (1.0 - speculation_ratio) * 30.0).clamp(0.0, 100.0)
        };

        let research_score = if has_research_deficit {
            base_score.min(45.0)
        } else {
            base_score
        };

        let verdict = if has_research_deficit {
            "RESEARCH_DEFICIT".to_string()
        } else if citations_count > 0 || factual_claims_count == 0 {
            "RESEARCH_GROUNDED".to_string()
        } else {
            "THEORETICAL".to_string()
        };

        let mut recommendations = Vec::new();
        if has_research_deficit {
            recommendations.push(
                "Research Deficit: Factual technical assertions made without citations. Verify against official documentation or code repository before answering."
                    .to_string(),
            );
        }
        if speculation_ratio > 0.3 {
            recommendations.push(
                "High Speculation: Stop guessing library behavior. Research the exact API specification."
                    .to_string(),
            );
        }

        ResearchReport {
            factual_claims_count,
            citations_count,
            evidence_ratio,
            speculation_ratio,
            has_research_deficit,
            unverified_claims: factual_claims,
            detected_sources,
            research_score,
            verdict,
            recommendations,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_research_grounded() {
        let text = "According to docs.rs and RFC 2024, tree-sitter v0.24 is compatible with Rust 2021.\nReference: https://github.com/tree-sitter/tree-sitter";
        let report = ResearchGate::audit(text);
        assert!(!report.has_research_deficit);
        assert!(report.citations_count > 0);
        assert_eq!(report.verdict, "RESEARCH_GROUNDED");
    }

    #[test]
    fn test_research_deficit() {
        let text = "Version v0.23 supports throughput of 50000 ops/s. It is also compatible with all v0.24 compilers without any changes.";
        let report = ResearchGate::audit(text);
        assert!(report.has_research_deficit);
        assert_eq!(report.verdict, "RESEARCH_DEFICIT");
        assert!(!report.recommendations.is_empty());
    }

    #[test]
    fn test_theoretical_no_claims() {
        let text = "Clean code principles emphasize readability and separation of concerns.";
        let report = ResearchGate::audit(text);
        assert!(!report.has_research_deficit);
        assert_eq!(report.verdict, "RESEARCH_GROUNDED");
    }
}
