//! Research Gate Engine: Forces AI to cite empirical evidence and verify claims before delivering output.

use crate::engine::text_utils::{smart_split_sentences, HEDGING_PHRASES};
use serde::{Deserialize, Serialize};
use std::path::Path;

/// 3-Tier Evidence Lifecycle state for technical assertions.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq)]
pub enum EvidenceStatus {
    /// Technical claim made with zero citations or supporting evidence
    Unsupported,
    /// Evidence/citation syntax present, but unverified authority or unverifiable source
    EvidencePresent,
    /// Deterministically verified evidence (valid RFC range, authoritative registry, or verified file)
    EvidenceVerified,
}

/// Detailed diagnostic analysis of an individual factual claim.
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct ClaimAnalysis {
    pub claim: String,
    pub claim_type: String, // "VERSION_SPECIFICATION", "BENCHMARK_PERFORMANCE", "API_COMPATIBILITY"
    pub evidence_required: bool,
    pub evidence_status: EvidenceStatus,
    pub is_verified: bool,
    pub remediation: String,
}

/// Report generated by the ResearchGate engine.
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct ResearchReport {
    /// Number of factual claims detected (versions, benchmarks, library compatibility, dates)
    pub factual_claims_count: usize,
    /// Total citations detected
    pub citations_count: usize,
    /// Authoritatively verified citations count
    pub verified_citations_count: usize,
    /// Citations present but from unverified or placeholder sources
    pub unverified_citations_count: usize,
    /// Evidence to claims ratio: verified_citations / max(claims, 1)
    pub evidence_ratio: f64,
    /// Ratio of speculative statements to total sentences
    pub speculation_ratio: f64,
    /// True if multiple factual claims exist without supporting evidence
    pub has_research_deficit: bool,
    /// Factual claims flagged as ungrounded or unverified
    pub unverified_claims: Vec<String>,
    /// Concrete evidence sources detected
    pub detected_sources: Vec<String>,
    /// Diagnostic analysis of each detected factual claim
    #[serde(default)]
    pub claim_analyses: Vec<ClaimAnalysis>,
    /// Grounding quality score (0.0 to 100.0)
    pub research_score: f64,
    /// Verdict: RESEARCH_GROUNDED, RESEARCH_DEFICIT, or THEORETICAL
    pub verdict: String,
    /// Actionable research recommendations
    pub recommendations: Vec<String>,
}

const AUTHORITATIVE_DOMAINS: &[&str] = &[
    "docs.rs",
    "crates.io",
    "github.com",
    "ietf.org",
    "w3.org",
    "developer.mozilla.org",
    "python.org",
    "go.dev",
    "pkg.go.dev",
    "kernel.org",
    "iso.org",
    "ieee.org",
    "rust-lang.org",
    "npmjs.com",
    "pypi.org",
];

const UNTRUSTED_OR_PLACEHOLDER_DOMAINS: &[&str] = &[
    "example.com",
    "example.org",
    "example.net",
    "fake.example",
    "test.com",
    "foo.bar",
    "localhost",
];

/// Curated registry of recognized, published IETF standard RFCs.
pub const KNOWN_RFC_REGISTRY: &[u32] = &[
    768, 791, 792, 793, 826, 854, 959, 1034, 1035, 1122, 1123, 1234, 1918, 2024,
    2045, 2046, 2119, 2131, 2326, 2616, 2818, 2821, 2822, 3261, 3339, 3492, 3550,
    3986, 4122, 4251, 4252, 4253, 4254, 4346, 4648, 5246, 5280, 5321, 5322, 5869,
    6066, 6265, 6455, 6749, 6750, 7230, 7231, 7232, 7233, 7234, 7235, 7515, 7519,
    7540, 7636, 8174, 8259, 8446, 9000, 9001, 9110, 9111, 9112, 9113, 9114, 9204,
    9218, 9293, 9440,
];

pub struct ResearchGate;

impl ResearchGate {
    /// Extracts the clean hostname from a URL string without protocol, port, or path.
    pub fn extract_hostname(raw_url: &str) -> Option<String> {
        let without_proto = raw_url
            .strip_prefix("https://")
            .or_else(|| raw_url.strip_prefix("http://"))?;

        let host_port = without_proto.split(['/', '?', '#']).next().unwrap_or("");
        let host = host_port.split(':').next().unwrap_or("").trim();
        if host.is_empty() {
            None
        } else {
            Some(host.to_string())
        }
    }

    /// Recognizes structured standard identifiers while rejecting bare acronym mentions.
    pub fn match_structured_standards(lower: &str) -> Vec<String> {
        let mut results = Vec::new();

        // Structured IEEE standards, e.g. "ieee 754", "ieee 802.11", "ieee standard"
        if let Some(pos) = lower.find("ieee") {
            let after = lower[pos + 4..].trim_start();
            if after.starts_with(|c: char| c.is_ascii_digit()) {
                let token: String = after
                    .chars()
                    .take_while(|c| c.is_alphanumeric() || *c == '.' || *c == '-')
                    .collect();
                results.push(format!("Recognized standard: IEEE {}", token));
            } else if after.starts_with("standard") || after.starts_with("std") {
                results.push("Recognized standard: IEEE Standard".to_string());
            }
        }

        // Structured ISO / ISO/IEC standards, e.g. "iso/iec 27001", "iso 9001"
        if let Some(pos) = lower.find("iso/iec") {
            let after = lower[pos + 7..].trim_start();
            if after.starts_with(|c: char| c.is_ascii_digit()) {
                let token: String = after
                    .chars()
                    .take_while(|c| c.is_ascii_digit() || *c == '-')
                    .collect();
                results.push(format!("Recognized standard: ISO/IEC {}", token));
            } else {
                results.push("Recognized standard: ISO/IEC specification".to_string());
            }
        } else if let Some(pos) = lower.find("iso") {
            let after = lower[pos + 3..].trim_start();
            if after.starts_with(|c: char| c.is_ascii_digit()) {
                let token: String = after
                    .chars()
                    .take_while(|c| c.is_ascii_digit() || *c == '-')
                    .collect();
                results.push(format!("Recognized standard: ISO {}", token));
            }
        }

        // W3C recommendation or spec
        if lower.contains("w3c recommendation")
            || lower.contains("w3c spec")
            || lower.contains("w3c standard")
        {
            results.push("Recognized standard: W3C Recommendation".to_string());
        }

        // ANSI standard
        if let Some(pos) = lower.find("ansi") {
            let after = lower[pos + 4..].trim_start_matches(|c: char| c == '/' || c.is_whitespace());
            if after.starts_with(|c: char| c.is_ascii_digit() || c.is_alphabetic()) && after.len() >= 3 {
                let token: String = after
                    .chars()
                    .take_while(|c| c.is_alphanumeric() || *c == '.' || *c == '-')
                    .collect();
                results.push(format!("Recognized standard: ANSI {}", token));
            }
        }

        results
    }

    /// Evaluates evidence citations present in a specific sentence.
    pub fn evaluate_evidence(sentence: &str) -> (Vec<String>, usize, usize) {
        let mut sources = Vec::new();
        let mut verified = 0;
        let mut unverified = 0;
        let lower = sentence.to_lowercase();

        // 1. URL check & strict hostname authority validation
        if let Some(idx) = lower.find("http://").or_else(|| lower.find("https://")) {
            let url_part = &sentence[idx..];
            let url_token = url_part.split_whitespace().next().unwrap_or("");
            let clean_url = url_token.trim_matches(|c: char| !c.is_alphanumeric() && c != '/' && c != ':' && c != '-' && c != '.' && c != '_');
            let lower_url = clean_url.to_lowercase();

            let host_opt = Self::extract_hostname(&lower_url);
            let is_placeholder = host_opt.as_ref().map(|h| {
                UNTRUSTED_OR_PLACEHOLDER_DOMAINS.iter().any(|&d| h == d || h.ends_with(&format!(".{}", d)))
            }).unwrap_or(false);

            let is_authoritative = host_opt.as_ref().map(|h| {
                AUTHORITATIVE_DOMAINS.iter().any(|&d| h == d || h.ends_with(&format!(".{}", d)))
            }).unwrap_or(false);

            if is_placeholder {
                sources.push(format!("Placeholder/unverified URL: '{}'", clean_url));
                unverified += 1;
            } else if is_authoritative {
                sources.push(format!("Authoritative documentation: '{}'", clean_url));
                verified += 1;
            } else {
                sources.push(format!("General web link (unverified authority): '{}'", clean_url));
                unverified += 1;
            }
        }

        // 2. RFC check & curated registry validation
        if let Some(rfc_idx) = lower.find("rfc") {
            let after_rfc = &sentence[rfc_idx + 3..];
            let rfc_num_str: String = after_rfc
                .chars()
                .skip_while(|c| c.is_whitespace() || *c == '-' || *c == ':')
                .take_while(|c| c.is_ascii_digit())
                .collect();
            if let Ok(num) = rfc_num_str.parse::<u32>() {
                if KNOWN_RFC_REGISTRY.binary_search(&num).is_ok() {
                    sources.push(format!("Verified IETF standard: RFC {}", num));
                    verified += 1;
                } else {
                    sources.push(format!("Uncataloged/unverified RFC number: RFC {}", num));
                    unverified += 1;
                }
            }
        }

        // 3. Local file path check (requires actual file existence on disk)
        for w in sentence.split_whitespace() {
            let token = w.trim_matches(['(', '[', '{', '"', '\'', '`', '<', '>']);
            let clean = token.trim_end_matches(['.', ',', ';', ':', '!', '?', ')', ']', '}', '"', '\'', '`']);
            if (clean.contains('/') || clean.contains('\\'))
                && (clean.ends_with(".rs")
                    || clean.ends_with(".ts")
                    || clean.ends_with(".js")
                    || clean.ends_with(".py")
                    || clean.ends_with(".go")
                    || clean.ends_with(".java")
                    || clean.ends_with(".json")
                    || clean.ends_with(".toml")
                    || clean.ends_with(".yaml")
                    || clean.starts_with("c:\\")
                    || clean.starts_with("d:\\"))
            {
                if Path::new(clean).exists() {
                    sources.push(format!("Verified local file path: '{}'", clean));
                    verified += 1;
                } else {
                    sources.push(format!("Unverified file reference (does not exist): '{}'", clean));
                    unverified += 1;
                }
            }
        }

        // 5. Recognized structured standards markers (rejects bare acronym mentions)
        for std_name in Self::match_structured_standards(&lower) {
            sources.push(std_name);
            verified += 1;
        }

        // 6. Empirical test or benchmark execution logs
        if (lower.contains("test result:") && lower.contains("ok"))
            || lower.contains("benchmark logs")
            || lower.contains("test coverage")
        {
            sources.push("Empirical execution or benchmark log".to_string());
            verified += 1;
        }

        (sources, verified, unverified)
    }

    /// Audits response text to verify that technical claims are backed by research and citations.
    pub fn audit(text: &str) -> ResearchReport {
        let trimmed = text.trim();
        if trimmed.is_empty() {
            return ResearchReport {
                factual_claims_count: 0,
                citations_count: 0,
                verified_citations_count: 0,
                unverified_citations_count: 0,
                evidence_ratio: 0.0,
                speculation_ratio: 0.0,
                has_research_deficit: false,
                unverified_claims: vec![],
                detected_sources: vec![],
                claim_analyses: vec![],
                research_score: 0.0,
                verdict: "INSUFFICIENT_EVIDENCE".to_string(),
                recommendations: vec!["Text is empty. No research to audit.".to_string()],
            };
        }

        let sentences = smart_split_sentences(trimmed);
        let total_sentences = sentences.len().max(1);

        let mut factual_claims = Vec::new();
        let mut claim_analyses = Vec::new();
        let mut detected_sources = Vec::new();
        let mut total_verified = 0;
        let mut total_unverified = 0;
        let mut speculation_count = 0;

        for sentence in &sentences {
            let lower = sentence.to_lowercase();

            // Evaluate evidence in this specific sentence
            let (sources, v_count, unv_count) = Self::evaluate_evidence(sentence);
            total_verified += v_count;
            total_unverified += unv_count;
            for s in sources {
                detected_sources.push(s);
            }

            // Factual claim detection: version strings, benchmarks, release dates
            let has_version_claim = lower.contains("version")
                || lower.contains("phiên bản")
                || sentence.split_whitespace().any(|word| {
                    let w = word.trim_matches(|c: char| !c.is_alphanumeric());
                    (w.starts_with('v') || w.starts_with('V'))
                        && w.len() >= 2
                        && w[1..].chars().next().map(|c| c.is_ascii_digit()).unwrap_or(false)
                });

            let has_benchmark_claim = lower.contains("ops/s")
                || lower.contains("benchmark")
                || lower.contains("throughput")
                || lower.contains("latency")
                || lower.contains("p99")
                || lower.contains("p95")
                || lower.contains("req/s")
                || sentence.split_whitespace().any(|w| {
                    let clean = w.trim_matches(|c: char| !c.is_alphanumeric());
                    clean.ends_with("ms")
                        && clean.len() >= 3
                        && clean.trim_end_matches("ms").chars().all(|c| c.is_ascii_digit() || c == '.')
                });

            let has_spec_claim = lower.contains("supports")
                || lower.contains("compatible with")
                || lower.contains("hỗ trợ")
                || lower.contains("tương thích");

            if has_benchmark_claim || has_version_claim || has_spec_claim {
                let claim_type = if has_benchmark_claim {
                    "BENCHMARK_PERFORMANCE"
                } else if has_version_claim {
                    "VERSION_SPECIFICATION"
                } else {
                    "API_COMPATIBILITY"
                };

                let evidence_status = if unv_count > 0 {
                    EvidenceStatus::EvidencePresent
                } else if v_count > 0 {
                    EvidenceStatus::EvidenceVerified
                } else {
                    EvidenceStatus::Unsupported
                };

                let is_verified = evidence_status == EvidenceStatus::EvidenceVerified;

                let remediation = match evidence_status {
                    EvidenceStatus::Unsupported => match claim_type {
                        "BENCHMARK_PERFORMANCE" => "Provide official benchmark URL, execution command, or test log to substantiate throughput/latency claims.".to_string(),
                        "VERSION_SPECIFICATION" => "Provide official release documentation URL or repository link validating version feature support.".to_string(),
                        _ => "Provide official API reference or specification documentation confirming compatibility.".to_string(),
                    },
                    EvidenceStatus::EvidencePresent => "Citation detected but unverified against authoritative registry/RFC database. Ground claim in official docs (docs.rs, ietf.org, github.com).".to_string(),
                    EvidenceStatus::EvidenceVerified => String::new(),
                };

                claim_analyses.push(ClaimAnalysis {
                    claim: sentence.trim().to_string(),
                    claim_type: claim_type.to_string(),
                    evidence_required: true,
                    evidence_status,
                    is_verified,
                    remediation,
                });

                if !is_verified {
                    factual_claims.push(sentence.trim().to_string());
                }
            }

            // Speculation detection
            if HEDGING_PHRASES.iter().any(|&h| lower.contains(h)) {
                speculation_count += 1;
            }
        }

        detected_sources.sort();
        detected_sources.dedup();

        let factual_claims_count = claim_analyses.len();
        let citations_count = total_verified + total_unverified;

        let evidence_ratio = if factual_claims_count == 0 {
            1.0
        } else {
            (total_verified as f64 / factual_claims_count as f64).min(2.0)
        };

        let speculation_ratio = speculation_count as f64 / total_sentences as f64;

        // Universal Grounding Axiom: Deficit triggers if ANY factual claim is unverified
        let ungrounded_claims: Vec<String> = claim_analyses
            .iter()
            .filter(|c| !c.is_verified)
            .map(|c| c.claim.clone())
            .collect();
        let has_research_deficit = !ungrounded_claims.is_empty();

        let verified_claims_count = claim_analyses.iter().filter(|c| c.is_verified).count();
        let claim_verification_ratio = if factual_claims_count == 0 {
            1.0
        } else {
            verified_claims_count as f64 / factual_claims_count as f64
        };

        let base_score = if factual_claims_count == 0 {
            95.0
        } else {
            (claim_verification_ratio * 70.0 + (1.0 - speculation_ratio) * 30.0).clamp(0.0, 100.0)
        };

        let research_score = if has_research_deficit {
            base_score.min(45.0)
        } else if total_unverified > 0 {
            base_score.min(60.0)
        } else {
            base_score
        };

        let verdict = if has_research_deficit {
            "RESEARCH_DEFICIT".to_string()
        } else if total_verified > 0 || factual_claims_count == 0 {
            "RESEARCH_GROUNDED".to_string()
        } else {
            "THEORETICAL".to_string()
        };

        let mut recommendations = Vec::new();
        if has_research_deficit {
            recommendations.push(
                "Research Deficit: Factual technical assertions made without authoritative citations. Verify against official documentation (docs.rs, ietf.org) before answering."
                    .to_string(),
            );
        }
        if total_unverified > 0 {
            recommendations.push(
                "Unverified Citations Detected: Replace placeholder or unrecognized URLs/RFCs with authoritative primary documentation."
                    .to_string(),
            );
        }
        if speculation_ratio > 0.3 {
            recommendations.push(
                "High Speculation: Stop guessing library behavior. Research the exact API specification."
                    .to_string(),
            );
        }

        ResearchReport {
            factual_claims_count,
            citations_count,
            verified_citations_count: total_verified,
            unverified_citations_count: total_unverified,
            evidence_ratio,
            speculation_ratio,
            has_research_deficit,
            unverified_claims: ungrounded_claims,
            detected_sources,
            claim_analyses,
            research_score,
            verdict,
            recommendations,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_research_grounded_authoritative() {
        let text = "According to docs.rs and RFC 2024, tree-sitter v0.24 is compatible with Rust 2021.\nReference: https://github.com/tree-sitter/tree-sitter";
        let report = ResearchGate::audit(text);
        assert!(!report.has_research_deficit);
        assert!(report.verified_citations_count > 0);
        assert_eq!(report.verdict, "RESEARCH_GROUNDED");
    }

    #[test]
    fn test_research_deficit_unsupported() {
        let text = "Version v0.23 supports throughput of 50000 ops/s. It is also compatible with all v0.24 compilers without any changes.";
        let report = ResearchGate::audit(text);
        assert!(report.has_research_deficit);
        assert_eq!(report.verdict, "RESEARCH_DEFICIT");
        assert!(!report.recommendations.is_empty());
    }

    #[test]
    fn test_placeholder_url_unverified() {
        let text = "Version v0.24 is 10x faster according to https://example.com/bench";
        let report = ResearchGate::audit(text);
        assert!(report.unverified_citations_count > 0);
        assert_eq!(report.claim_analyses[0].evidence_status, EvidenceStatus::EvidencePresent);
        assert!(!report.claim_analyses[0].is_verified);
    }

    #[test]
    fn test_fake_rfc_rejected() {
        let text = "According to RFC 999999, latency is 0.5 ms.";
        let report = ResearchGate::audit(text);
        assert!(report.unverified_citations_count > 0);
        assert_eq!(report.claim_analyses[0].evidence_status, EvidenceStatus::EvidencePresent);
        assert!(!report.claim_analyses[0].is_verified);
    }

    #[test]
    fn test_uncataloged_rfc_rejected() {
        let text = "According to RFC 9999, throughput is 100000 ops/s.";
        let report = ResearchGate::audit(text);
        assert!(report.has_research_deficit);
        assert!(report.unverified_citations_count > 0);
        assert_eq!(report.claim_analyses[0].evidence_status, EvidenceStatus::EvidencePresent);
        assert!(!report.claim_analyses[0].is_verified);
    }

    #[test]
    fn test_bare_acronym_not_evidence() {
        let text = "According to IEEE and ISO, latency is 10 ms.";
        let report = ResearchGate::audit(text);
        assert!(report.has_research_deficit);
        assert_eq!(report.verified_citations_count, 0);
    }

    #[test]
    fn test_structured_standard_verified() {
        let text = "According to IEEE 754 and ISO/IEC 27001, version v1.0 is verified.";
        let report = ResearchGate::audit(text);
        assert!(!report.has_research_deficit);
        assert!(report.verified_citations_count >= 2);
    }

    #[test]
    fn test_mixed_claims_triggers_deficit() {
        let text = "According to https://docs.rs/serde, version v1.0 is stable.\nMeanwhile latency of v2.0 is 0.01ms as per RFC 9999.";
        let report = ResearchGate::audit(text);
        assert!(report.has_research_deficit);
        assert_eq!(report.verdict, "RESEARCH_DEFICIT");
        assert_eq!(report.unverified_claims.len(), 1);
    }

    #[test]
    fn test_theoretical_no_claims() {
        let text = "Clean code principles emphasize readability and separation of concerns.";
        let report = ResearchGate::audit(text);
        assert!(!report.has_research_deficit);
        assert_eq!(report.verdict, "RESEARCH_GROUNDED");
    }
}
