#![allow(unused_imports)]

pub mod code_evaluator;
pub mod confidence_checker;
pub mod constraint_checker;
pub mod diff_checker;
pub mod foresight_checker;
pub mod plan_tracker;
pub mod research_checker;
pub mod text_evaluator;
pub mod unified_audit;

pub use code_evaluator::execute_code_evaluator;
pub use confidence_checker::execute_confidence_checker;
pub use constraint_checker::execute_constraint_checker;
pub use diff_checker::execute_diff_checker;
pub use foresight_checker::execute_foresight_checker;
pub use plan_tracker::execute_plan_tracker;
pub use research_checker::execute_research_checker;
pub use text_evaluator::execute_text_evaluator;
pub use unified_audit::{
    execute_unified_audit, AuditViolation, PlanTaskInput, SeveritySummary, UnifiedAuditInput,
    UnifiedAuditReport, ViolationSeverity,
};

use crate::mcp::protocol::Tool;
use serde_json::json;

pub fn get_available_tools() -> Vec<Tool> {
    vec![
        Tool {
            name: "verify_agent".to_string(),
            description: "Unified AI Agent Governance & Behavioral Verification Gate (formerly math_audit_cognition). Evaluates decisions as ALLOW, WARN, or BLOCK across 6 verification pillars: constraints, plan DAG, text density, epistemic calibration, empirical research, and proactive foresight.".to_string(),
            input_schema: json!({
                "type": "object",
                "properties": {
                    "mode": {
                        "type": "string",
                        "enum": ["quick", "standard", "deep"],
                        "default": "standard",
                        "description": "Audit depth: 'quick' (<1ms light checks), 'standard' (default full 6-pillar audit), 'deep' (maximum rigor)"
                    },
                    "user_requirements": {
                        "type": "array",
                        "items": { "type": "string" },
                        "description": "List of explicit requirements and constraints from the user"
                    },
                    "planned_tasks": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "id": { "type": "string" },
                                "name": { "type": "string" },
                                "dependencies": { "type": "array", "items": { "type": "string" } }
                            },
                            "required": ["id", "name"]
                        },
                        "description": "List of planned tasks forming the DAG"
                    },
                    "executed_steps": {
                        "type": "array",
                        "items": { "type": "string" },
                        "description": "Sequence of task IDs executed so far"
                    },
                    "draft_response": {
                        "type": "string",
                        "description": "Draft response text AI intends to send to the user"
                    },
                    "code_snippet": {
                        "type": "string",
                        "description": "Source code snippet generated by AI"
                    },
                    "language": {
                        "type": "string",
                        "description": "Programming language (rust, typescript, javascript, python, go, java, c, cpp, etc.)"
                    }
                }
            }),
        },
        Tool {
            name: "verify_dag".to_string(),
            description: "Tracks plan execution against a Directed Acyclic Graph (DAG) (formerly math_track_dag). Detects topological violations, cycles, plan coverage ratio C, and scope creep W.".to_string(),
            input_schema: json!({
                "type": "object",
                "properties": {
                    "tasks": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "id": { "type": "string" },
                                "name": { "type": "string" },
                                "dependencies": { "type": "array", "items": { "type": "string" } }
                            },
                            "required": ["id", "name"]
                        }
                    },
                    "executed_steps": {
                        "type": "array",
                        "items": { "type": "string" }
                    }
                },
                "required": ["tasks"]
            }),
        },
        Tool {
            name: "verify_code".to_string(),
            description: "Analyzes code using Tree-sitter AST, McCabe Cyclomatic Complexity, Halstead Metrics, Maintainability Index, and boundary checks (formerly math_eval_code).".to_string(),
            input_schema: json!({
                "type": "object",
                "properties": {
                    "code": { "type": "string", "description": "Source code to analyze" },
                    "language": { "type": "string", "description": "Language: rust, typescript, python, go, java, c, cpp, etc." }
                },
                "required": ["code"]
            }),
        },
        Tool {
            name: "verify_diff".to_string(),
            description: "Analyzes code diffs using Longest Common Subsequence (LCS) (formerly math_eval_diff), measuring change ratio, cyclomatic and maintainability deltas, functions affected, and regression risk.".to_string(),
            input_schema: json!({
                "type": "object",
                "properties": {
                    "before_code": { "type": "string", "description": "Original source code" },
                    "after_code": { "type": "string", "description": "Modified source code" },
                    "language": { "type": "string", "description": "Language: rust, typescript, python, go, java, c, cpp, etc." }
                },
                "required": ["before_code", "after_code"]
            }),
        },
        Tool {
            name: "verify_text".to_string(),
            description: "Evaluates text through Information Theory (Shannon Entropy, Information Density) (formerly math_eval_text), Kolmogorov compression estimation, readability (Flesch-Kincaid, Gunning Fog), and AI filler detection.".to_string(),
            input_schema: json!({
                "type": "object",
                "properties": {
                    "text": { "type": "string", "description": "Text to evaluate" }
                },
                "required": ["text"]
            }),
        },
        Tool {
            name: "verify_confidence".to_string(),
            description: "Epistemic Calibration Gate (formerly math_confidence). Evaluates draft text for overconfidence, unverified certainty claims, hedging ratio, assertion density, and self-contradictions.".to_string(),
            input_schema: json!({
                "type": "object",
                "properties": {
                    "text": { "type": "string", "description": "AI response text to evaluate" }
                },
                "required": ["text"]
            }),
        },
        Tool {
            name: "verify_research".to_string(),
            description: "Forces research and factual grounding (formerly math_audit_research). Scans text for technical claims, checks for empirical citations (URLs, RFCs, paths, logs), and flags research deficits.".to_string(),
            input_schema: json!({
                "type": "object",
                "properties": {
                    "text": { "type": "string", "description": "Response text to audit for research grounding" }
                },
                "required": ["text"]
            }),
        },
        Tool {
            name: "verify_foresight".to_string(),
            description: "Evaluates proactive foresight (formerly math_eval_foresight): defensive error handling, boundary/edge case coverage, verification strategy, and flags lazy shallow plans.".to_string(),
            input_schema: json!({
                "type": "object",
                "properties": {
                    "text": { "type": "string", "description": "Plan or draft explanation text" },
                    "code": { "type": "string", "description": "Source code snippet (optional)" },
                    "requirements_count": { "type": "integer", "description": "Total user requirements count" },
                    "planned_tasks_count": { "type": "integer", "description": "Total planned DAG tasks count" }
                }
            }),
        },
        Tool {
            name: "verify_constraints".to_string(),
            description: "Formal Set Theory constraint verification with n-gram Jaccard semantic matching and dynamic negation pattern contradiction detection (formerly math_verify_constraints).".to_string(),
            input_schema: json!({
                "type": "object",
                "properties": {
                    "requirements": {
                        "type": "array",
                        "items": { "type": "string" },
                        "description": "User demands/specifications"
                    },
                    "implementations": {
                        "type": "array",
                        "items": { "type": "string" },
                        "description": "Actual delivered features/claims"
                    }
                },
                "required": ["requirements", "implementations"]
            }),
        },
    ]
}
